#FROM ubuntu:20.04
FROM scratch
ADD ubuntu-focal-oci-amd64-root.tar.gz /
#ADD pkgs/ubuntu-bionic-oci-amd64-root.tar.gz /

# Update the image to the latest packages
RUN apt-get update && apt-get upgrade -y

# Install basic tools
RUN apt-get install iputils-ping -y
RUN apt-get install net-tools -y
RUN apt-get install samba -y
RUN apt-get install vim -y
RUN apt-get install wget curl -y
RUN apt-get install openssh-client -y
RUN apt-get install postfix -y

# Copy configuration files
COPY valiases.cf /etc/postfix/
COPY useraliases.cf /etc/postfix/
COPY groupaliases.cf /etc/postfix/
COPY mailbox.cf /etc/postfix/
COPY vdomains.cf /etc/postfix/
COPY login.cf /etc/postfix/
COPY mailname /etc/mailname

# Make entrypoint for docker run
RUN echo "#!/bin/bash" >> /docker-entrypoint.sh
RUN echo "postfix start" >> /docker-entrypoint.sh
RUN echo "tail -f /dev/null" >> /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Start Omada
CMD ["/docker-entrypoint.sh"]