#FROM ubuntu:20.04
FROM scratch
ADD ubuntu-focal-oci-amd64-root.tar.gz /
#ADD pkgs/ubuntu-bionic-oci-amd64-root.tar.gz /
#ADD pkgs/Omada_SDN_Controller_v5.0.30_linux_x64.tar.gz /

#
# Update the image to the latest packages
RUN apt-get update && apt-get upgrade -y

#
# Install dependencies
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install wget curl jsvc -y

# Install mongoDB
RUN apt install -y software-properties-common gnupg apt-transport-https ca-certificates
RUN apt install -y mongodb

# Get the Omada install pkg (downloaded in the same directory of Dockerfile)
RUN wget https://static.tp-link.com/upload/software/2022/202201/20220120/Omada_SDN_Controller_v5.0.30_linux_x64.tar.gz

# Install Omada
RUN tar zxvf Omada_SDN_Controller_v5.0.30_linux_x64.tar.gz
RUN WORKDIR Omada_SDN_Controller_v5.0.30_linux_x64
RUN yes | ./install.sh

# Start Omada
CMD ["tpeap start"]
